### ISSUE TITLE
Emax lightning 30a unsuccessful automatic and manual flashing

### ISSUE THREAD

**Issue by Spc8** [blheli-configurator/blheli-configurator#53]
I am trying to update the ESCs firmware as suggested by Emax:

https://www.emaxmodel.com/blog/AmandaChen/

"As our Lightning 20A and 30A ESC come out earlier than official BLHELI program,and old Lightning 20A and 30A ESCs’ program based on our Nano firmware.Due to the different hardware configuration, Lightning 20A &30A ESC could not be flashed directly by any hex file of NANO 20a ESC,but now could find the lightning 20A &30A ESC in official hex: https://github.com/bitdump/BLHeli/tree/master/SiLabs/Hex%20files.

We have had many customers flash the Lightning 20A and Lightning 30A ESCs with Nano20A 14.6 firmware and having problems. PLEASE DO NOT     FLASH LIGHTNING 20A and 30A ESC WITH WRONG FIRMWARE. Lightning 20A and 30A ESCs are factory flashed with 14.2 and performs flawlessly.  Although BlHeli Suite recommends Nano20A 14.6 firmware, "EMAX Lightning 20A" firmware for multirotors must be used if updating to 14.6. Please check version of firmware before flashing."

I have a Lux V2 FC, Blheli configurator reads correctly my ESCs as Emax Nano20A. 
I tried automatic and manual flashing with different failures as you will see in the log file.
What am I doing wrong?

Thanks for your help!

Log file attached:

Running - OS: <strong>MacOS</strong>, Chrome: <strong>58.0.3029.96</strong>, Configurator: <strong>1.0.13</strong>
Running - OS: <strong>MacOS</strong>, Chrome: <strong>58.0.3029.96</strong>, Configurator: <strong>1.0.13</strong>
Running - OS: <strong>MacOS</strong>, Chrome: <strong>58.0.3029.96</strong>, Configurator: <strong>1.0.13</strong>
Running - OS: <strong>MacOS</strong>, Chrome: <strong>58.0.3029.96</strong>, Configurator: <strong>1.0.13</strong>
Running - OS: <strong>MacOS</strong>, Chrome: <strong>58.0.3029.96</strong>, Configurator: <strong>1.0.13</strong>
Running - OS: <strong>MacOS</strong>, Chrome: <strong>58.0.3029.96</strong>, Configurator: <strong>1.0.13</strong>
Selecting last used port: /dev/tty.usbmodem1411
Connecting to: /dev/tty.usbmodem1411
SERIAL: Connection opened with ID: 1, Baud: 115200
Serial port <span style="color: green">successfully</span> opened with ID: 1
MultiWii API version <span style="color: green">received</span> - <strong>1.31.0</strong>
Flight controller info, identifier: <strong>BTFL</strong>, version: <strong>3.1.7</strong>
Running firmware released on: <strong>Apr  3 2017 22:09:37</strong>
Board: <strong>LUXR</strong>, version: <strong>0</strong>
Unique device ID <span style="color: green">received</span> - <strong>0x2800225633571120333131</strong>
Reading setup
sending cmd_DeviceInitFlash 0 0
received cmd_DeviceInitFlash ACK_OK 0 48,243,99,1
sending cmd_DeviceRead 1a00 112
received cmd_DeviceRead ACK_OK 1a00 14,2,20,9,9,4,255,3,255,10,1,1,1,85,170,1,255,255,255,255,255,3,255,255,255,5,239,40,80,4,255,2,0,122,255,1,1,0,3,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,35,69,77,65,88,78,97,110,111,50,48,65,35,32,32,32,35,66,76,72,69,76,73,35,70,51,51,48,35,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32
sending cmd_DeviceReset 0 0
received cmd_DeviceReset ACK_OK 0 0
sending cmd_DeviceInitFlash 0 1
received cmd_DeviceInitFlash ACK_OK 0 48,243,99,1
sending cmd_DeviceRead 1a00 112
received cmd_DeviceRead ACK_OK 1a00 14,2,20,9,9,4,255,3,255,10,1,1,1,85,170,1,255,255,255,255,255,3,255,255,255,5,240,40,80,4,255,2,0,122,255,1,1,0,3,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,35,69,77,65,88,78,97,110,111,50,48,65,35,32,32,32,35,66,76,72,69,76,73,35,70,51,51,48,35,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32
sending cmd_DeviceReset 0 1
received cmd_DeviceReset ACK_OK 0 0
sending cmd_DeviceInitFlash 0 2
received cmd_DeviceInitFlash ACK_OK 0 48,243,99,1
sending cmd_DeviceRead 1a00 112
received cmd_DeviceRead ACK_OK 1a00 14,2,20,9,9,4,255,3,255,10,1,1,1,85,170,1,255,255,255,255,255,3,255,255,255,5,240,40,80,4,255,2,0,122,255,1,1,0,3,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,35,69,77,65,88,78,97,110,111,50,48,65,35,32,32,32,35,66,76,72,69,76,73,35,70,51,51,48,35,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32
sending cmd_DeviceReset 0 2
received cmd_DeviceReset ACK_OK 0 0
sending cmd_DeviceInitFlash 0 3
received cmd_DeviceInitFlash ACK_OK 0 48,243,99,1
sending cmd_DeviceRead 1a00 112
received cmd_DeviceRead ACK_OK 1a00 14,2,20,9,9,4,255,3,255,10,1,1,1,85,170,1,255,255,255,255,255,3,255,255,255,5,240,40,80,4,255,2,0,122,255,1,1,0,3,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,35,69,77,65,88,78,97,110,111,50,48,65,35,32,32,32,35,66,76,72,69,76,73,35,70,51,51,48,35,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32
sending cmd_DeviceReset 0 3
received cmd_DeviceReset ACK_OK 0 0
Reading setup <span style="color: green">finished</span>
Could not load firmware for EMAX Lightning 20A MULTI 14.9: <span style="color: red">File is unavailable</span>
Loading file from ~/Download/BLHeli-master/SiLabs/Hex files/EMAX_Lightning_20A_MULTI_REV14_9.HEX
Loaded file ~/Download/BLHeli-master/SiLabs/Hex files/EMAX_Lightning_20A_MULTI_REV14_9.HEX
ESC 1: flashing <strong>started</strong>
sending cmd_DeviceInitFlash 0 0
received cmd_DeviceInitFlash ACK_OK 0 48,243,99,1
sending cmd_DeviceRead 1a00 112
received cmd_DeviceRead ACK_OK 1a00 14,2,20,9,9,4,255,3,255,10,1,1,1,85,170,1,255,255,255,255,255,3,255,255,255,5,239,40,80,4,255,2,0,122,255,1,1,0,3,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,35,69,77,65,88,78,97,110,111,50,48,65,35,32,32,32,35,66,76,72,69,76,73,35,70,51,51,48,35,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32
ESC 1: flashing <span style="color: red">failed</span> - <strong>Error: LAYOUT found <span style="color: red">#EMAXNano20A#</span>, <strong>#EMAX_Ltng_20A#</strong> expected
    at checkESCAndMCU (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/blheli_configurator.js:711:43)
    at _fulfilled (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:794:58)
    at self.promiseDispatch.done (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:823:34)
    at Promise.promise.promiseDispatch (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:756:17)
    at chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:564:48
    at flush (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:110:21)
    at n.exports (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:13226)
    at y.(anonymous function) (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:28018)
    at Number.b (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:27863)
    at MessagePort.x (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:27885)</strong>
ESC 2: flashing <strong>started</strong>
sending cmd_DeviceInitFlash 0 1
received cmd_DeviceInitFlash ACK_OK 0 48,243,99,1
sending cmd_DeviceRead 1a00 112
received cmd_DeviceRead ACK_OK 1a00 14,2,20,9,9,4,255,3,255,10,1,1,1,85,170,1,255,255,255,255,255,3,255,255,255,5,240,40,80,4,255,2,0,122,255,1,1,0,3,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,35,69,77,65,88,78,97,110,111,50,48,65,35,32,32,32,35,66,76,72,69,76,73,35,70,51,51,48,35,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32
ESC 2: flashing <span style="color: red">failed</span> - <strong>Error: LAYOUT found <span style="color: red">#EMAXNano20A#</span>, <strong>#EMAX_Ltng_20A#</strong> expected
    at checkESCAndMCU (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/blheli_configurator.js:711:43)
    at _fulfilled (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:794:58)
    at self.promiseDispatch.done (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:823:34)
    at Promise.promise.promiseDispatch (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:756:17)
    at chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:564:48
    at flush (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:110:21)
    at n.exports (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:13226)
    at y.(anonymous function) (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:28018)
    at Number.b (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:27863)
    at MessagePort.x (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:27885)</strong>
ESC 3: flashing <strong>started</strong>
sending cmd_DeviceInitFlash 0 2
received cmd_DeviceInitFlash ACK_OK 0 48,243,99,1
sending cmd_DeviceRead 1a00 112
received cmd_DeviceRead ACK_OK 1a00 14,2,20,9,9,4,255,3,255,10,1,1,1,85,170,1,255,255,255,255,255,3,255,255,255,5,240,40,80,4,255,2,0,122,255,1,1,0,3,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,35,69,77,65,88,78,97,110,111,50,48,65,35,32,32,32,35,66,76,72,69,76,73,35,70,51,51,48,35,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32
ESC 3: flashing <span style="color: red">failed</span> - <strong>Error: LAYOUT found <span style="color: red">#EMAXNano20A#</span>, <strong>#EMAX_Ltng_20A#</strong> expected
    at checkESCAndMCU (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/blheli_configurator.js:711:43)
    at _fulfilled (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:794:58)
    at self.promiseDispatch.done (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:823:34)
    at Promise.promise.promiseDispatch (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:756:17)
    at chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:564:48
    at flush (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:110:21)
    at n.exports (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:13226)
    at y.(anonymous function) (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:28018)
    at Number.b (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:27863)
    at MessagePort.x (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:27885)</strong>
ESC 4: flashing <strong>started</strong>
sending cmd_DeviceInitFlash 0 3
received cmd_DeviceInitFlash ACK_OK 0 48,243,99,1
sending cmd_DeviceRead 1a00 112
received cmd_DeviceRead ACK_OK 1a00 14,2,20,9,9,4,255,3,255,10,1,1,1,85,170,1,255,255,255,255,255,3,255,255,255,5,240,40,80,4,255,2,0,122,255,1,1,0,3,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,35,69,77,65,88,78,97,110,111,50,48,65,35,32,32,32,35,66,76,72,69,76,73,35,70,51,51,48,35,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32
ESC 4: flashing <span style="color: red">failed</span> - <strong>Error: LAYOUT found <span style="color: red">#EMAXNano20A#</span>, <strong>#EMAX_Ltng_20A#</strong> expected
    at checkESCAndMCU (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/blheli_configurator.js:711:43)
    at _fulfilled (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:794:58)
    at self.promiseDispatch.done (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:823:34)
    at Promise.promise.promiseDispatch (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:756:17)
    at chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:564:48
    at flush (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:110:21)
    at n.exports (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:13226)
    at y.(anonymous function) (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:28018)
    at Number.b (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:27863)
    at MessagePort.x (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:27885)</strong>
sending cmd_InterfaceExit 0 0
received cmd_InterfaceExit ACK_OK 0 0
SERIAL: Connection with ID: 1 closed, Sent: 1058 bytes, Received: 2152 bytes
Connecting to: /dev/tty.usbmodem1411
Selecting last used port: /dev/tty.usbmodem1411
Connecting to: /dev/tty.usbmodem1411
SERIAL: Connection opened with ID: 1, Baud: 115200
Serial port <span style="color: green">successfully</span> opened with ID: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
Connection <span style="color: red">failed</span>, ensure that you have selected the <span style="color: yellow">correct port</span> or <span style="color: yellow">restart</span> your device.
MSP data request timed-out: 1
SERIAL: Connection with ID: 1 closed, Sent: 66 bytes, Received: 0 bytes
Connecting to: /dev/tty.usbmodem1411
SERIAL: Connection opened with ID: 2, Baud: 115200
Serial port <span style="color: green">successfully</span> opened with ID: 2
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
Connection <span style="color: red">failed</span>, ensure that you have selected the <span style="color: yellow">correct port</span> or <span style="color: yellow">restart</span> your device.
MSP data request timed-out: 1
SERIAL: Connection with ID: 2 closed, Sent: 66 bytes, Received: 0 bytes
Connecting to: /dev/tty.usbmodem1411
SERIAL: Connection opened with ID: 3, Baud: 115200
Serial port <span style="color: green">successfully</span> opened with ID: 3
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
[object Object]
SERIAL: Connection with ID: 3 closed, Sent: 36 bytes, Received: 0 bytes
PortHandler - Removed: /dev/tty.usbmodem1411,/dev/cu.usbmodem1411
PortHandler - Found: /dev/tty.usbmodem1411,/dev/cu.usbmodem1411
Connecting to: /dev/tty.usbmodem1411
Selecting last used port: /dev/tty.usbmodem1411
Connecting to: /dev/tty.usbmodem1411
SERIAL: Connection opened with ID: 1, Baud: 115200
Serial port <span style="color: green">successfully</span> opened with ID: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
Connection <span style="color: red">failed</span>, ensure that you have selected the <span style="color: yellow">correct port</span> or <span style="color: yellow">restart</span> your device.
MSP data request timed-out: 1
SERIAL: Connection with ID: 1 closed, Sent: 66 bytes, Received: 0 bytes
Selecting last used port: /dev/tty.usbmodem1411
Connecting to: /dev/tty.usbmodem1411
SERIAL: Connection opened with ID: 1, Baud: 115200
Serial port <span style="color: green">successfully</span> opened with ID: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
MSP data request timed-out: 1
Connection <span style="color: red">failed</span>, ensure that you have selected the <span style="color: yellow">correct port</span> or <span style="color: yellow">restart</span> your device.
MSP data request timed-out: 1
SERIAL: Connection with ID: 1 closed, Sent: 66 bytes, Received: 0 bytes
PortHandler - Removed: /dev/tty.usbmodem1411,/dev/cu.usbmodem1411
PortHandler - Found: /dev/tty.usbmodem1411,/dev/cu.usbmodem1411
Connecting to: /dev/tty.usbmodem1411
SERIAL: Connection opened with ID: 1, Baud: 115200
Serial port <span style="color: green">successfully</span> opened with ID: 1
MultiWii API version <span style="color: green">received</span> - <strong>1.31.0</strong>
Flight controller info, identifier: <strong>BTFL</strong>, version: <strong>3.1.7</strong>
Running firmware released on: <strong>Apr  3 2017 22:09:37</strong>
Board: <strong>LUXR</strong>, version: <strong>0</strong>
Unique device ID <span style="color: green">received</span> - <strong>0x2800225633571120333131</strong>
Reading setup
sending cmd_DeviceInitFlash 0 0
received cmd_DeviceInitFlash ACK_OK 0 48,243,99,1
sending cmd_DeviceRead 1a00 112
received cmd_DeviceRead ACK_OK 1a00 14,2,20,9,9,4,255,3,255,10,1,1,1,85,170,1,255,255,255,255,255,3,255,255,255,5,239,40,80,4,255,2,0,122,255,1,1,0,3,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,35,69,77,65,88,78,97,110,111,50,48,65,35,32,32,32,35,66,76,72,69,76,73,35,70,51,51,48,35,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32
sending cmd_DeviceReset 0 0
received cmd_DeviceReset ACK_OK 0 0
sending cmd_DeviceInitFlash 0 1
received cmd_DeviceInitFlash ACK_OK 0 48,243,99,1
sending cmd_DeviceRead 1a00 112
received cmd_DeviceRead ACK_OK 1a00 14,2,20,9,9,4,255,3,255,10,1,1,1,85,170,1,255,255,255,255,255,3,255,255,255,5,240,40,80,4,255,2,0,122,255,1,1,0,3,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,35,69,77,65,88,78,97,110,111,50,48,65,35,32,32,32,35,66,76,72,69,76,73,35,70,51,51,48,35,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32
sending cmd_DeviceReset 0 1
received cmd_DeviceReset ACK_OK 0 0
sending cmd_DeviceInitFlash 0 2
received cmd_DeviceInitFlash ACK_OK 0 48,243,99,1
sending cmd_DeviceRead 1a00 112
received cmd_DeviceRead ACK_OK 1a00 14,2,20,9,9,4,255,3,255,10,1,1,1,85,170,1,255,255,255,255,255,3,255,255,255,5,240,40,80,4,255,2,0,122,255,1,1,0,3,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,35,69,77,65,88,78,97,110,111,50,48,65,35,32,32,32,35,66,76,72,69,76,73,35,70,51,51,48,35,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32
sending cmd_DeviceReset 0 2
received cmd_DeviceReset ACK_OK 0 0
sending cmd_DeviceInitFlash 0 3
received cmd_DeviceInitFlash ACK_OK 0 48,243,99,1
sending cmd_DeviceRead 1a00 112
received cmd_DeviceRead ACK_OK 1a00 14,2,20,9,9,4,255,3,255,10,1,1,1,85,170,1,255,255,255,255,255,3,255,255,255,5,240,40,80,4,255,2,0,122,255,1,1,0,3,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,35,69,77,65,88,78,97,110,111,50,48,65,35,32,32,32,35,66,76,72,69,76,73,35,70,51,51,48,35,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32
sending cmd_DeviceReset 0 3
received cmd_DeviceReset ACK_OK 0 0
Reading setup <span style="color: green">finished</span>
Could not load firmware for EMAX Lightning 20A MULTI 14.9: <span style="color: red">File is unavailable</span>
Loading file from ~/Download/BLHeli-master/SiLabs/Hex files/EMAX_20A_MULTI_REV14_9.HEX
Loaded file ~/Download/BLHeli-master/SiLabs/Hex files/EMAX_20A_MULTI_REV14_9.HEX
ESC 1: flashing <strong>started</strong>
sending cmd_DeviceInitFlash 0 0
received cmd_DeviceInitFlash ACK_OK 0 48,243,99,1
sending cmd_DeviceRead 1a00 112
received cmd_DeviceRead ACK_OK 1a00 14,2,20,9,9,4,255,3,255,10,1,1,1,85,170,1,255,255,255,255,255,3,255,255,255,5,239,40,80,4,255,2,0,122,255,1,1,0,3,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,35,69,77,65,88,78,97,110,111,50,48,65,35,32,32,32,35,66,76,72,69,76,73,35,70,51,51,48,35,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32
ESC 1: flashing <span style="color: red">failed</span> - <strong>Error: LAYOUT found <span style="color: red">#EMAXNano20A#</span>, <strong>#EMAX20A#</strong> expected
    at checkESCAndMCU (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/blheli_configurator.js:711:43)
    at _fulfilled (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:794:58)
    at self.promiseDispatch.done (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:823:34)
    at Promise.promise.promiseDispatch (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:756:17)
    at chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:564:48
    at flush (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:110:21)
    at n.exports (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:13226)
    at y.(anonymous function) (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:28018)
    at Number.b (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:27863)
    at MessagePort.x (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:27885)</strong>
ESC 2: flashing <strong>started</strong>
sending cmd_DeviceInitFlash 0 1
received cmd_DeviceInitFlash ACK_OK 0 48,243,99,1
sending cmd_DeviceRead 1a00 112
received cmd_DeviceRead ACK_OK 1a00 14,2,20,9,9,4,255,3,255,10,1,1,1,85,170,1,255,255,255,255,255,3,255,255,255,5,240,40,80,4,255,2,0,122,255,1,1,0,3,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,35,69,77,65,88,78,97,110,111,50,48,65,35,32,32,32,35,66,76,72,69,76,73,35,70,51,51,48,35,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32
ESC 2: flashing <span style="color: red">failed</span> - <strong>Error: LAYOUT found <span style="color: red">#EMAXNano20A#</span>, <strong>#EMAX20A#</strong> expected
    at checkESCAndMCU (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/blheli_configurator.js:711:43)
    at _fulfilled (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:794:58)
    at self.promiseDispatch.done (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:823:34)
    at Promise.promise.promiseDispatch (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:756:17)
    at chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:564:48
    at flush (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:110:21)
    at n.exports (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:13226)
    at y.(anonymous function) (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:28018)
    at Number.b (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:27863)
    at MessagePort.x (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:27885)</strong>
ESC 3: flashing <strong>started</strong>
sending cmd_DeviceInitFlash 0 2
received cmd_DeviceInitFlash ACK_OK 0 48,243,99,1
sending cmd_DeviceRead 1a00 112
received cmd_DeviceRead ACK_OK 1a00 14,2,20,9,9,4,255,3,255,10,1,1,1,85,170,1,255,255,255,255,255,3,255,255,255,5,240,40,80,4,255,2,0,122,255,1,1,0,3,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,35,69,77,65,88,78,97,110,111,50,48,65,35,32,32,32,35,66,76,72,69,76,73,35,70,51,51,48,35,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32
ESC 3: flashing <span style="color: red">failed</span> - <strong>Error: LAYOUT found <span style="color: red">#EMAXNano20A#</span>, <strong>#EMAX20A#</strong> expected
    at checkESCAndMCU (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/blheli_configurator.js:711:43)
    at _fulfilled (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:794:58)
    at self.promiseDispatch.done (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:823:34)
    at Promise.promise.promiseDispatch (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:756:17)
    at chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:564:48
    at flush (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:110:21)
    at n.exports (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:13226)
    at y.(anonymous function) (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:28018)
    at Number.b (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:27863)
    at MessagePort.x (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:27885)</strong>
ESC 4: flashing <strong>started</strong>
sending cmd_DeviceInitFlash 0 3
received cmd_DeviceInitFlash ACK_OK 0 48,243,99,1
sending cmd_DeviceRead 1a00 112
received cmd_DeviceRead ACK_OK 1a00 14,2,20,9,9,4,255,3,255,10,1,1,1,85,170,1,255,255,255,255,255,3,255,255,255,5,240,40,80,4,255,2,0,122,255,1,1,0,3,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,255,35,69,77,65,88,78,97,110,111,50,48,65,35,32,32,32,35,66,76,72,69,76,73,35,70,51,51,48,35,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32,32
ESC 4: flashing <span style="color: red">failed</span> - <strong>Error: LAYOUT found <span style="color: red">#EMAXNano20A#</span>, <strong>#EMAX20A#</strong> expected
    at checkESCAndMCU (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/blheli_configurator.js:711:43)
    at _fulfilled (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:794:58)
    at self.promiseDispatch.done (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:823:34)
    at Promise.promise.promiseDispatch (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:756:17)
    at chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:564:48
    at flush (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/q.js:110:21)
    at n.exports (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:13226)
    at y.(anonymous function) (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:28018)
    at Number.b (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:27863)
    at MessagePort.x (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/libraries/polyfill.min.js:1:27885)</strong>

**Comment by claytonbakerjr** [comment]
I have a similar problem.
 flashing failed - Error: LAYOUT found #A_H_20#, #A_H_25# expected at checkESCAndMCU
LittleBee Spring 30amp escs.
Bought 4, 2 came with AH20 16.6 and 2 came with AH25 16.5. Flashed the AH25 to 16,6 no problem, tried to bring the AH20's up to the same but it will not. What happens if I select to ignore MCU.
What can I do.
Using BLHeli COnfigurator 1.0.14
