### ISSUE TITLE
One esc is no more visible after fault by flashing

### ISSUE THREAD

**Issue by gryzli133** [blheli-configurator/blheli-configurator#93]
I was flashing ESC 4in1 of my Leader 120 with Omnibus FC. The log with the fault:

2017-11-22 @ 19:22:37 -- ESC 1: flashing started
2017-11-22 @ 19:23:23 -- Writing setup
2017-11-22 @ 19:23:25 -- ESC 1: 112 byte(s) written
2017-11-22 @ 19:23:25 -- Writing setup finished
2017-11-22 @ 19:23:25 -- ESC 1: flashing finished in 48.120000000000005 seconds
2017-11-22 @ 19:23:25 -- ESC 2: flashing started
2017-11-22 @ 19:23:37 -- ESC 2: flashing failed - Error: cmd_DeviceRead ACK_D_GENERAL_ERROR at recvCallback (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/_4way_if.js:198:37) at chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/_4way_if.js:296:29 at Array.forEach () at Object.onread (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/_4way_if.js:278:18) at read_serial (chrome-extension://mejfjggmbnocnfibbibmoogocnjbcjnk/js/serial_backend.js:234:15) at EventImpl.dispatchToListener (extensions::event_bindings:403:22) at Event.publicClassPrototype.(anonymous function) [as dispatchToListener] (extensions::utils:138:26) at EventImpl.dispatch_ (extensions::event_bindings:387:35) at dispatchArgs (extensions::event_bindings:260:26) at dispatchEvent (extensions::event_bindings:269:7)
2017-11-22 @ 19:23:37 -- ESC 3: flashing started
2017-11-22 @ 19:24:25 -- Writing setup
2017-11-22 @ 19:24:26 -- ESC 3: 112 byte(s) written
2017-11-22 @ 19:24:27 -- Writing setup finished
2017-11-22 @ 19:24:27 -- ESC 3: flashing finished in 49.962 seconds
2017-11-22 @ 19:24:27 -- ESC 4: flashing started
2017-11-22 @ 19:25:02 -- Writing setup
2017-11-22 @ 19:25:03 -- ESC 4: no changes
2017-11-22 @ 19:25:03 -- Writing setup finished
2017-11-22 @ 19:25:03 -- ESC 4: flashing finished in 36.287 seconds

After that I can only see ESP 1,3 and 4. Number 2 is missing. Also I cannot control it from Betaflight...

**Comment by gryzli133** [comment]
I have solved it by soldering the two pins on the board and upload new firmware through arduino. Very good job anyway! :)
